/**
 * Global Error Code Catalog
 *
 * This taxonomy provides stable, module-agnostic error codes that clients
 * can rely on for error handling and UI feedback.
 */
export enum ErrorCode {
  // --- AUTH ENTITY ERRORS ---
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_ACCOUNT_DEACTIVATED = 'AUTH_ACCOUNT_DEACTIVATED',

  // --- VALIDATION & REQUEST ERRORS ---
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  MISSING_PARAMETER = 'MISSING_PARAMETER',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  REQUEST_TOO_LARGE = 'REQUEST_TOO_LARGE',

  // --- RESOURCE ERRORS ---
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RESOURCE_GONE = 'RESOURCE_GONE',
  ALREADY_EXISTS = 'ALREADY_EXISTS',

  // --- RATE LIMIT ERRORS ---
  THROTTLED = 'THROTTLED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // --- STELLAR / CONTRACT ERRORS ---
  STELLAR_ERROR = 'STELLAR_ERROR',
  CONTRACT_INVOCATION_FAILED = 'CONTRACT_INVOCATION_FAILED',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',

  // --- INTERNAL ERRORS ---
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
